license = "CC0-1.0"

modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Me!"
description = "This is an example description! Tell everyone what your mod is about!"

logoFile = "assets/template/icon.png"
#displayURL = "..."
#issueTrackerUrl = "..."

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
#versionRange = "${minecraft}"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api},)"
ordering = "AFTER"
side = "BOTH"
